// Copyright 2026 jeff-kittrell. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGsiCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gsi",
		Short: "Operations on status",
	}

	cmd.AddCommand(newGsiListListaccountsCmd(flags))
	cmd.AddCommand(newGsiListPassiveJsonCmd(flags))
	cmd.AddCommand(newGsiListStatusCmd(flags))
	return cmd
}
