// Copyright 2026 jeff-kittrell. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMapsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "maps",
		Short: "Operations on js",
	}

	cmd.AddCommand(newMapsListGen204Cmd(flags))
	cmd.AddCommand(newMapsListJsCmd(flags))
	return cmd
}
