// Copyright 2026 jeff-kittrell. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMapsListJsCmd(flags *rootFlags) *cobra.Command {
	var flagCallback string
	var flagChannel string
	var flagLanguage string
	var flagLibraries string
	var flagRegion string
	var flagV string

	cmd := &cobra.Command{
		Use:   "list-js",
		Short: "GET /maps/api/js",
		Example: "  expedia-cars-pp-cli maps list-js",
		Annotations: map[string]string{"pp:endpoint": "maps.list_js", "pp:method": "GET", "pp:path": "/maps/api/js", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/maps/api/js"
			params := map[string]string{}
			if flagCallback != "" {
				params["callback"] = fmt.Sprintf("%v", flagCallback)
			}
			if flagChannel != "" {
				params["channel"] = fmt.Sprintf("%v", flagChannel)
			}
			if flagLanguage != "" {
				params["language"] = fmt.Sprintf("%v", flagLanguage)
			}
			if flagLibraries != "" {
				params["libraries"] = fmt.Sprintf("%v", flagLibraries)
			}
			if flagRegion != "" {
				params["region"] = fmt.Sprintf("%v", flagRegion)
			}
			if flagV != "" {
				params["v"] = fmt.Sprintf("%v", flagV)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "maps", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCallback, "callback", "", "")
	cmd.Flags().StringVar(&flagChannel, "channel", "", "")
	cmd.Flags().StringVar(&flagLanguage, "language", "", "")
	cmd.Flags().StringVar(&flagLibraries, "libraries", "", "")
	cmd.Flags().StringVar(&flagRegion, "region", "", "")
	cmd.Flags().StringVar(&flagV, "v", "", "")

	return cmd
}
