// Copyright 2026 jeff-kittrell. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTypeaheadPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagBrowser string
	var flagClient string
	var flagDest bool
	var flagDevice string
	var flagExpuserid string
	var flagFeatures string
	var flagFormat string
	var flagGuid string
	var flagListing bool
	var flagLob string
	var flagLocale string
	var flagMaxresults int
	var flagPersonalize bool
	var flagRecentHistoryEnabled bool
	var flagRegiontype int
	var flagSiteid string

	cmd := &cobra.Command{
		Use:   "typeahead",
		Short: "GET /api/v4/typeahead/Las Vegas, NV, United States of America (LAS-Harry Reid Intl.)",
		Long:  "Shortcut for 'typeahead list_Las Vegas, NV, United States of America (LAS_Harry Reid Intl.)'. GET /api/v4/typeahead/Las Vegas, NV, United States of America (LAS-Harry Reid Intl.)",
		Example: "  expedia-cars-pp-cli typeahead",
		Annotations: map[string]string{"pp:endpoint": "typeahead.list_Las Vegas, NV, United States of America (LAS_Harry Reid Intl.)", "pp:method": "GET", "pp:path": "/api/v4/typeahead/Las Vegas, NV, United States of America (LAS-Harry Reid Intl.)", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v4/typeahead/Las Vegas, NV, United States of America (LAS-Harry Reid Intl.)"
			params := map[string]string{}
			if flagBrowser != "" {
				params["browser"] = fmt.Sprintf("%v", flagBrowser)
			}
			if flagClient != "" {
				params["client"] = fmt.Sprintf("%v", flagClient)
			}
			if flagDest != false {
				params["dest"] = fmt.Sprintf("%v", flagDest)
			}
			if flagDevice != "" {
				params["device"] = fmt.Sprintf("%v", flagDevice)
			}
			if flagExpuserid != "" {
				params["expuserid"] = fmt.Sprintf("%v", flagExpuserid)
			}
			if flagFeatures != "" {
				params["features"] = fmt.Sprintf("%v", flagFeatures)
			}
			if flagFormat != "" {
				params["format"] = fmt.Sprintf("%v", flagFormat)
			}
			if flagGuid != "" {
				params["guid"] = fmt.Sprintf("%v", flagGuid)
			}
			if flagListing != false {
				params["listing"] = fmt.Sprintf("%v", flagListing)
			}
			if flagLob != "" {
				params["lob"] = fmt.Sprintf("%v", flagLob)
			}
			if flagLocale != "" {
				params["locale"] = fmt.Sprintf("%v", flagLocale)
			}
			if flagMaxresults != 0 {
				params["maxresults"] = fmt.Sprintf("%v", flagMaxresults)
			}
			if flagPersonalize != false {
				params["personalize"] = fmt.Sprintf("%v", flagPersonalize)
			}
			if flagRecentHistoryEnabled != false {
				params["recentHistoryEnabled"] = fmt.Sprintf("%v", flagRecentHistoryEnabled)
			}
			if flagRegiontype != 0 {
				params["regiontype"] = fmt.Sprintf("%v", flagRegiontype)
			}
			if flagSiteid != "" {
				params["siteid"] = fmt.Sprintf("%v", flagSiteid)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "typeahead", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagBrowser, "browser", "", "")
	cmd.Flags().StringVar(&flagClient, "client", "", "")
	cmd.Flags().BoolVar(&flagDest, "dest", false, "")
	cmd.Flags().StringVar(&flagDevice, "device", "", "")
	cmd.Flags().StringVar(&flagExpuserid, "expuserid", "", "")
	cmd.Flags().StringVar(&flagFeatures, "features", "", "")
	cmd.Flags().StringVar(&flagFormat, "format", "", "")
	cmd.Flags().StringVar(&flagGuid, "guid", "", "")
	cmd.Flags().BoolVar(&flagListing, "listing", false, "")
	cmd.Flags().StringVar(&flagLob, "lob", "", "")
	cmd.Flags().StringVar(&flagLocale, "locale", "", "")
	cmd.Flags().IntVar(&flagMaxresults, "maxresults", 0, "")
	cmd.Flags().BoolVar(&flagPersonalize, "personalize", false, "")
	cmd.Flags().BoolVar(&flagRecentHistoryEnabled, "recent-history-enabled", false, "")
	cmd.Flags().IntVar(&flagRegiontype, "regiontype", 0, "")
	cmd.Flags().StringVar(&flagSiteid, "siteid", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
