// Copyright 2026 jeff-kittrell. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPageadPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagAsync int
	var flagAuid string
	var flagBg string
	var flagCapi int
	var flagCategory string
	var flagCv int
	var flagData string
	var flagDma int
	var flagEcMode string
	var flagEme string
	var flagEn string
	var flagFmt int
	var flagFrm int
	var flagFst int
	var flagGapGtb int
	var flagGcd string
	var flagGclCtr string
	var flagGcs string
	var flagGtm string
	var flagGtmEe int
	var flagGuid string
	var flagHn string
	var flagLabel string
	var flagNpa int
	var flagPscdl string
	var flagRandom int
	var flagRcb int
	var flagTagExp string
	var flagTiba string
	var flagUH int
	var flagUW int
	var flagUaa string
	var flagUab int
	var flagUafvl string
	var flagUam string
	var flagUamb int
	var flagUap string
	var flagUapv string
	var flagUaw int
	var flagUrl string
	var flagUserId string

	cmd := &cobra.Command{
		Use:   "pagead <id>",
		Short: "GET /pagead/conversion/{id}/",
		Long:  "Shortcut for 'pagead get_conversion'. GET /pagead/conversion/{id}/",
		Example: "  expedia-cars-pp-cli pagead 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "pagead.get_conversion", "pp:method": "GET", "pp:path": "/pagead/conversion/{id}/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/pagead/conversion/{id}/"
			if len(args) < 23 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[22])
			params := map[string]string{}
			if flagAsync != 0 {
				params["async"] = fmt.Sprintf("%v", flagAsync)
			}
			if flagAuid != "" {
				params["auid"] = fmt.Sprintf("%v", flagAuid)
			}
			if flagBg != "" {
				params["bg"] = fmt.Sprintf("%v", flagBg)
			}
			if flagCapi != 0 {
				params["capi"] = fmt.Sprintf("%v", flagCapi)
			}
			if flagCategory != "" {
				params["category"] = fmt.Sprintf("%v", flagCategory)
			}
			if flagCv != 0 {
				params["cv"] = fmt.Sprintf("%v", flagCv)
			}
			if flagData != "" {
				params["data"] = fmt.Sprintf("%v", flagData)
			}
			if flagDma != 0 {
				params["dma"] = fmt.Sprintf("%v", flagDma)
			}
			if flagEcMode != "" {
				params["ec_mode"] = fmt.Sprintf("%v", flagEcMode)
			}
			if flagEme != "" {
				params["eme"] = fmt.Sprintf("%v", flagEme)
			}
			if flagEn != "" {
				params["en"] = fmt.Sprintf("%v", flagEn)
			}
			if flagFmt != 0 {
				params["fmt"] = fmt.Sprintf("%v", flagFmt)
			}
			if flagFrm != 0 {
				params["frm"] = fmt.Sprintf("%v", flagFrm)
			}
			if flagFst != 0 {
				params["fst"] = fmt.Sprintf("%v", flagFst)
			}
			if flagGapGtb != 0 {
				params["gap.gtb"] = fmt.Sprintf("%v", flagGapGtb)
			}
			if flagGcd != "" {
				params["gcd"] = fmt.Sprintf("%v", flagGcd)
			}
			if flagGclCtr != "" {
				params["gcl_ctr"] = fmt.Sprintf("%v", flagGclCtr)
			}
			if flagGcs != "" {
				params["gcs"] = fmt.Sprintf("%v", flagGcs)
			}
			if flagGtm != "" {
				params["gtm"] = fmt.Sprintf("%v", flagGtm)
			}
			if flagGtmEe != 0 {
				params["gtm_ee"] = fmt.Sprintf("%v", flagGtmEe)
			}
			if flagGuid != "" {
				params["guid"] = fmt.Sprintf("%v", flagGuid)
			}
			if flagHn != "" {
				params["hn"] = fmt.Sprintf("%v", flagHn)
			}
			if flagLabel != "" {
				params["label"] = fmt.Sprintf("%v", flagLabel)
			}
			if flagNpa != 0 {
				params["npa"] = fmt.Sprintf("%v", flagNpa)
			}
			if flagPscdl != "" {
				params["pscdl"] = fmt.Sprintf("%v", flagPscdl)
			}
			if flagRandom != 0 {
				params["random"] = fmt.Sprintf("%v", flagRandom)
			}
			if flagRcb != 0 {
				params["rcb"] = fmt.Sprintf("%v", flagRcb)
			}
			if flagTagExp != "" {
				params["tag_exp"] = fmt.Sprintf("%v", flagTagExp)
			}
			if flagTiba != "" {
				params["tiba"] = fmt.Sprintf("%v", flagTiba)
			}
			if flagUH != 0 {
				params["u_h"] = fmt.Sprintf("%v", flagUH)
			}
			if flagUW != 0 {
				params["u_w"] = fmt.Sprintf("%v", flagUW)
			}
			if flagUaa != "" {
				params["uaa"] = fmt.Sprintf("%v", flagUaa)
			}
			if flagUab != 0 {
				params["uab"] = fmt.Sprintf("%v", flagUab)
			}
			if flagUafvl != "" {
				params["uafvl"] = fmt.Sprintf("%v", flagUafvl)
			}
			if flagUam != "" {
				params["uam"] = fmt.Sprintf("%v", flagUam)
			}
			if flagUamb != 0 {
				params["uamb"] = fmt.Sprintf("%v", flagUamb)
			}
			if flagUap != "" {
				params["uap"] = fmt.Sprintf("%v", flagUap)
			}
			if flagUapv != "" {
				params["uapv"] = fmt.Sprintf("%v", flagUapv)
			}
			if flagUaw != 0 {
				params["uaw"] = fmt.Sprintf("%v", flagUaw)
			}
			if flagUrl != "" {
				params["url"] = fmt.Sprintf("%v", flagUrl)
			}
			if flagUserId != "" {
				params["userId"] = fmt.Sprintf("%v", flagUserId)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "pagead", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagAsync, "async", 0, "")
	cmd.Flags().StringVar(&flagAuid, "auid", "", "")
	cmd.Flags().StringVar(&flagBg, "bg", "", "")
	cmd.Flags().IntVar(&flagCapi, "capi", 0, "")
	cmd.Flags().StringVar(&flagCategory, "category", "", "")
	cmd.Flags().IntVar(&flagCv, "cv", 0, "")
	cmd.Flags().StringVar(&flagData, "data", "", "")
	cmd.Flags().IntVar(&flagDma, "dma", 0, "")
	cmd.Flags().StringVar(&flagEcMode, "ec-mode", "", "")
	cmd.Flags().StringVar(&flagEme, "eme", "", "")
	cmd.Flags().StringVar(&flagEn, "en", "", "")
	cmd.Flags().IntVar(&flagFmt, "fmt", 0, "")
	cmd.Flags().IntVar(&flagFrm, "frm", 0, "")
	cmd.Flags().IntVar(&flagFst, "fst", 0, "")
	cmd.Flags().IntVar(&flagGapGtb, "gap-gtb", 0, "")
	cmd.Flags().StringVar(&flagGcd, "gcd", "", "")
	cmd.Flags().StringVar(&flagGclCtr, "gcl-ctr", "", "")
	cmd.Flags().StringVar(&flagGcs, "gcs", "", "")
	cmd.Flags().StringVar(&flagGtm, "gtm", "", "")
	cmd.Flags().IntVar(&flagGtmEe, "gtm-ee", 0, "")
	cmd.Flags().StringVar(&flagGuid, "guid", "", "")
	cmd.Flags().StringVar(&flagHn, "hn", "", "")
	cmd.Flags().StringVar(&flagLabel, "label", "", "")
	cmd.Flags().IntVar(&flagNpa, "npa", 0, "")
	cmd.Flags().StringVar(&flagPscdl, "pscdl", "", "")
	cmd.Flags().IntVar(&flagRandom, "random", 0, "")
	cmd.Flags().IntVar(&flagRcb, "rcb", 0, "")
	cmd.Flags().StringVar(&flagTagExp, "tag-exp", "", "")
	cmd.Flags().StringVar(&flagTiba, "tiba", "", "")
	cmd.Flags().IntVar(&flagUH, "u-h", 0, "")
	cmd.Flags().IntVar(&flagUW, "u-w", 0, "")
	cmd.Flags().StringVar(&flagUaa, "uaa", "", "")
	cmd.Flags().IntVar(&flagUab, "uab", 0, "")
	cmd.Flags().StringVar(&flagUafvl, "uafvl", "", "")
	cmd.Flags().StringVar(&flagUam, "uam", "", "")
	cmd.Flags().IntVar(&flagUamb, "uamb", 0, "")
	cmd.Flags().StringVar(&flagUap, "uap", "", "")
	cmd.Flags().StringVar(&flagUapv, "uapv", "", "")
	cmd.Flags().IntVar(&flagUaw, "uaw", 0, "")
	cmd.Flags().StringVar(&flagUrl, "url", "", "")
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
