// Copyright 2026 jeff-kittrell. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTargetingServicePromotedCmd(flags *rootFlags) *cobra.Command {
	var flag int
	var flagAdProvider string
	var flagApp bool
	var flagCanTrack bool
	var flagDateEnd string
	var flagDateStart string
	var flagDest int
	var flagLocResolver string
	var flagOrigin int
	var flagPageName string
	var flagPpid string
	var flagSiteId string
	var flagSource string
	var flagUuid string

	cmd := &cobra.Command{
		Use:   "targeting-service",
		Short: "GET /targeting-service/v3/adinfo",
		Long:  "Shortcut for 'targeting-service list_adinfo'. GET /targeting-service/v3/adinfo",
		Example: "  expedia-cars-pp-cli targeting-service",
		Annotations: map[string]string{"pp:endpoint": "targeting-service.list_adinfo", "pp:method": "GET", "pp:path": "/targeting-service/v3/adinfo", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/targeting-service/v3/adinfo"
			params := map[string]string{}
			if flag != 0 {
				params["_"] = fmt.Sprintf("%v", flag)
			}
			if flagAdProvider != "" {
				params["adProvider"] = fmt.Sprintf("%v", flagAdProvider)
			}
			if flagApp != false {
				params["app"] = fmt.Sprintf("%v", flagApp)
			}
			if flagCanTrack != false {
				params["canTrack"] = fmt.Sprintf("%v", flagCanTrack)
			}
			if flagDateEnd != "" {
				params["dateEnd"] = fmt.Sprintf("%v", flagDateEnd)
			}
			if flagDateStart != "" {
				params["dateStart"] = fmt.Sprintf("%v", flagDateStart)
			}
			if flagDest != 0 {
				params["dest"] = fmt.Sprintf("%v", flagDest)
			}
			if flagLocResolver != "" {
				params["locResolver"] = fmt.Sprintf("%v", flagLocResolver)
			}
			if flagOrigin != 0 {
				params["origin"] = fmt.Sprintf("%v", flagOrigin)
			}
			if flagPageName != "" {
				params["pageName"] = fmt.Sprintf("%v", flagPageName)
			}
			if flagPpid != "" {
				params["ppid"] = fmt.Sprintf("%v", flagPpid)
			}
			if flagSiteId != "" {
				params["siteId"] = fmt.Sprintf("%v", flagSiteId)
			}
			if flagSource != "" {
				params["source"] = fmt.Sprintf("%v", flagSource)
			}
			if flagUuid != "" {
				params["uuid"] = fmt.Sprintf("%v", flagUuid)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "targeting-service", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flag, "", 0, "")
	cmd.Flags().StringVar(&flagAdProvider, "ad-provider", "", "")
	cmd.Flags().BoolVar(&flagApp, "app", false, "")
	cmd.Flags().BoolVar(&flagCanTrack, "can-track", false, "")
	cmd.Flags().StringVar(&flagDateEnd, "date-end", "", "")
	cmd.Flags().StringVar(&flagDateStart, "date-start", "", "")
	cmd.Flags().IntVar(&flagDest, "dest", 0, "")
	cmd.Flags().StringVar(&flagLocResolver, "loc-resolver", "", "")
	cmd.Flags().IntVar(&flagOrigin, "origin", 0, "")
	cmd.Flags().StringVar(&flagPageName, "page-name", "", "")
	cmd.Flags().StringVar(&flagPpid, "ppid", "", "")
	cmd.Flags().StringVar(&flagSiteId, "site-id", "", "")
	cmd.Flags().StringVar(&flagSource, "source", "", "")
	cmd.Flags().StringVar(&flagUuid, "uuid", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
